name: echo

services:
  memory:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    image: ifelsedotone/echo:latest
    ports:
      - "8000:8000"
      - "8501:8501"
    env_file:
      - ../.env
    depends_on:
      - memory
    volumes:
      - ../plugins/src/echo_plugins:/usr/src/echo/plugins
    healthcheck:
      test:
        ["CMD-SHELL", "wget -qO- http://localhost:8000/ | grep -q 'Echo AI'"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
